print("Hello")
print("WWWWW")
print("OOOOO")
print("RRRRR")
print("LLLLL")
print("DDDDD")
print("!!!!!")
player = input('What is your name?')
print(player), print("Please type yes if this is your name.")
import colorama
from colorama import Fore , Back , Style
import time
colorama.init(autoreset=True)
input()
# Use Colorama
print(Fore.WHITE + 'Welcome to this interview for...', end = ' ')
time.sleep(1)
print(Fore.RED + 'the', end = ' ')
print(Fore.YELLOW + 'best', end = ' ')
print(Fore.GREEN + 'job', end = ' ')
print(Fore.BLUE + 'in', end = ' ')
print(Fore.MAGENTA + 'the', end = ' ')
print(Fore.BLACK + 'world!', end = ' ') 
print('Please answer the following questions thoughtfully.')
print()
print()
print()
age = input('What is your age?')
print()
hobbies = input('What are your favorite hobbies?')
print()
three = input("If you're late for a meeting but you run into a problem, do you think you have enough problem-solving skills to make it to the meeting in time?")
print()     
four = input("On a scale of 1 to 5, where 5 represents the highest optimistic level, how optimistic do you think you are? Please provide the truth. We can use the lie detector to tell if you're lying.")
print()
five = input("If you see a sign that is crooked but no one else moves from their place, will you move and fix the sign? Type yes or no.")
print()
print("Please review the following information to make sure it is correct...")
print("Your name is"), print(player)
print("You are"), print(age), print("years old.")
print("You like"), print(hobbies)
print("You answered"), print(three), print("to having enough problem solving skills.")
print("You have an optimistic level of"), print(four)
print("You answered"), print(five), print("to fixing the sign.")
yes = input("Please type yes if the information is correct. Else, restart the page/game.")
print()
print()
print()
print()
print("Great! We will review the information and let you know if you are accepted.")
print()
print('a few moments later...')
print()
print("We have reviewed the information and have come to a decision!")
print("You are..................................................................................................................................................................................................................................................")
time.sleep(5)
print()
print()
print()
print()
print('AAAAA',     'CCCCC',     'CCCCC',     'EEEEE',     'PPPPP',     'TTTTT',     'EEEEE',     'DDDDD', sep ='   ')
print('A   A',     'C    ',     'C    ',     'E    ',     'P   P',     '  T  ',     'E    ',     'D   D', sep ='   ')
print('AAAAA',     'C    ',     'C    ',     'EEEEE',     'PPPPP',     '  T  ',     'EEEEE',     'D   D', sep ='   ')
print('A   A',     'C    ',     'C    ',     'E    ',     'P    ',     '  T  ',     'E    ',     'D  D ', sep ='   ')
print('A   A',     'CCCCC',     'CCCCC',     'EEEEE',     'P   ',      '  T  ',     'EEEEE',     'D    ', sep ='   ')
print()
print()
print("Just kidding... there will be another round of interviews shortly!")
print()
print("The End")
